### ISSUE TITLE
After opening user talk page by undoing edits, the “vanarticle” parameter doesn't work well with space

### ISSUE THREAD

**Issue by EtaoinWu** [Xi-Plus/twinkle#1]
There is a bug about `vanarticle` parameter generated by the "undo" tool of Twinkle.

If there are spaces mixed in the name of the (undo-ed) article (e.g. `Magic the Gathering`, then the `vanarticle=Magic+the+Gathering`.

Then if you use the [user warning tool](https://en.wikipedia.org/wiki/Wikipedia:WikiProject_User_warnings), the "page link" will use `+` (plus sign) instead of ` ` (space) and will generate wrong Wikitext.

**Comment by Xi-Plus** [comment]
I can't reproduce it. In version a6b7470, The url is `vanarticle=Magic%20the%20Gathering` in usertalk page after rollbacked.
