### ISSUE TITLE
管理員用快速刪除的自定義理由時在日誌會丟失最後的0

### ISSUE THREAD

**Issue by sunny00217wm** [Xi-Plus/twinkle#100]
參見[https://t.me/wikipedia_zh_help/33895](https://t.me/wikipedia_zh_help/33895)

**Comment by Xi-Plus** [comment]
@sunny00217wm 您最近有測試並復現嗎？

**Comment by sunny00217wm** [comment]
請看title，在下並非管理員，不可能做此測試

**Comment by Xi-Plus** [comment]
看起來這個問題昨天已經修復了，而且不是Twinkle的問題，是站內Lua模組的問題。

另外可以使用以下語法呼叫管理介面
```javascript
Morebits.userIsSysop = true;
Twinkle.speedy.callback();
```
