### ISSUE TITLE
Twinkle标记功能问题

### ISSUE THREAD

**Issue by xiaobiaoMC** [Xi-Plus/twinkle#132]
2050年7月24日晚使用twinkle的标记功能添加{{Expand language}}时，tw将原先标记完成的{{Unreferenced}}模板删除(oldid=60750820)。而编辑摘要并没有显示我移除了{{Unreferenced}}标记，并且在tw执行时的对话框显示「未找到{{Unreferenced}}标记」。发现问题后，我随即在公共沙盒中测试，仍然如此，所以来提报该问题。

**Comment by Xi-Plus** [comment]
https://zh.wikipedia.org/w/index.php?diff=60759897
https://zh.wikipedia.org/w/index.php?diff=60759901
無法重現， @xiaobiaoMC 請詳述操作步驟

**Comment by Hamishcn** [comment]
2050年。。

**Comment by xiaobiaoMC** [comment]
刚才在沙盒重新试了一下，并没有发现该问题重新出现，可能是当时网络问题。当该问题再次出现时，重新开启Issue吧。（这个问题出现的莫名其妙，并且在出现这个问题之前不久，也出现了Flow页面警告不成功的情况，待几时便成功了。确实有可能是网络问题。）
