### ISSUE TITLE
Tag: Unable to find template

### ISSUE THREAD

**Issue by Stang-wm** [Xi-Plus/twinkle#140]
于 [GNU计划](https://zh.wikipedia.org/wiki/GNU計劃) 内无法移除 Expand language 模板，其他模板移除则表现正常。
另外简体界面信息[似乎没有完善](https://github.com/Xi-Plus/twinkle/blob/master/modules/friendlytag.js#L1468)。
![image](https://user-images.githubusercontent.com/18418456/89119740-3af4ae00-d4e3-11ea-8dd2-3d56b222aa63.png)

**Comment by Xi-Plus** [comment]
該模板是{{Expand English}}，[已在站內修復模板](https://zh.wikipedia.org/w/index.php?title=Template%3AExpand_English&diff=prev&oldid=60896466)，請再嘗試

**Comment by Hamishcn** [comment]
理想状态下界面信息会在下一次大补完善

**Comment by Stang-wm** [comment]
看起来依旧修好了，感谢。
