### ISSUE TITLE
warn: 修復在Flow上預覽警告模板功能

### ISSUE THREAD

**Issue by Xi-Plus** [Xi-Plus/twinkle#147]
在Flow上預覽時會渲染出整個Flow頁面，而沒有警告模板

**Comment by zcccccc1** [comment]
另外，好像不能在Flow讨论页警告了，我点了警告，1分钟都没有用

**Comment by Xi-Plus** [comment]
@zcccccc1 請詳述哪個頁面、您的預設警告層級、您選擇的層級及模板為何？建議您開新的issues或在站內報告。

**Comment by Hamishcn** [comment]
不知道和[https://phabricator.wikimedia.org/T259565](T259565)有没有关系
