### ISSUE TITLE
增加ANM的提報

### ISSUE THREAD

**Issue by Xi-Plus** [Xi-Plus/twinkle#15]

**Comment by Xi-Plus** [comment]
個人認為
1. 這功能並不常使用
2. 要進行ANM提報的使用者應該對於報告內容詳細敘述，使用TW這樣的小工具並不會增快多少速度，不像是於報告LTA/VOA可以快速選擇理由以求迅速提報
所以沒必要做此功能，該請求無限期擱置直到上述想法有所改變。

**Comment by Hamishcn** [comment]
Then close.
