### ISSUE TITLE
标记 Expert needed 不易搜索、不易输入主题（子分类）

### ISSUE THREAD

**Issue by yfdyh000** [Xi-Plus/twinkle#171]
**錯誤/問題描述**
1. [模板](https://zh.wikipedia.org/wiki/Template:Expert_needed) [diff](https://zh.wikipedia.org/w/index.php?title=Template:Expert_needed/doc&diff=29070433&oldid=29070253) “但这种用法已经过时，今后的模板调用，请指明subject参数。”
2. 输入“[专家](https://zh.wikipedia.org/wiki/Template:%E4%B8%93%E5%AE%B6)”无法找到。

**重現步驟**
1. 在任意条目页面，打开 TW-标记 对话框。
2. 输入“专”
3. 勾选Expert needed。看到“哪个领域的专家”输入框。

**預期結果**
1. 筛选框输入"专家"时也列出该模板，通过如别名机制（如有），或者描述改为例如“需要精通或熟悉本主题的专业人士（专家）参与及协助编辑”。
2. “领域”链接到[分类](https://zh.wikipedia.org/wiki/Category:%E9%9C%80%E8%A6%81%E4%B8%93%E4%B8%9A%E4%BA%BA%E5%A3%AB%E5%85%B3%E6%B3%A8%E7%9A%84%E9%A1%B5%E9%9D%A2)或学科列表，以便了解应输入什么作主题。
3. 如果尚未支持，支持指定最多3个主题，用 | 分隔。
4. 是否将领域参数从可选改为警告或强制。

**Comment by Xi-Plus** [comment]
1. 沒有別名機制，以修改描述解決。
2. 技術上不支援加入連結，僅可使用純文字，暫未處理。
3. 已改為可附加3個參數。
4. 第一個參數已改為強制。
