### ISSUE TITLE
Feature Request: {{Current person}}

### ISSUE THREAD

**Issue by Emojigit** [Xi-Plus/twinkle#173]
Twinkle has no Current person template option, so I need to [add it manualy](https://zh.wikipedia.org/w/index.php?title=%E8%B3%80%E9%8C%A6%E9%BA%97&oldid=63820089). I hope TW has this function.

**Comment by Xi-Plus** [comment]
經過檢查模板的使用情況，我認為該模板的使用率沒有高到需要加入共通使用的模板列表內，但是如果您個人常使用該模板，您可以在 https://zh.wikipedia.org/wiki/Wikipedia:Twinkle/参数设置#tag 將其加到自訂的模板列表內。若有異議請於本單留言，若一段時間後情況改變，請開新單請求。感謝您的建議。
