### ISSUE TITLE
block: 開放非管理員使用標記功能

### ISSUE THREAD

**Issue by Xi-Plus** [Xi-Plus/twinkle#211]
我想有少數的使用者應該很常用這個功能，或許可考慮用opt-in的方式開放讓他們使用。

**Comment by hamishinyuu** [comment]
如果用opt-in的话，TW下拉菜单的外显也是“封禁”吧，感觉有些奇怪。

**Comment by sunny00217wm** [comment]
@hamishinyuu 保護都叫"保護"了

**Comment by hamishinyuu** [comment]
> @hamishinyuu 保護都叫"保護"了

当我没说

**Comment by Emojigit** [comment]
@Xi-Plus 我認爲可以以以下的方式調用：（python風格code）
if privs["sysop"] == True or settings["not-admin-block"] == True:
    element.block.show()
