### ISSUE TITLE
xfd: 提刪內容模型為javascript時提刪失敗

### ISSUE THREAD

**Issue by sunny00217wm** [Xi-Plus/twinkle#226]
提刪內容模型為javascript時，會因為不存在section=0而失敗（故未提交到提刪頁），然而模板已經掛上去了

https://t.me/wikipedia_zh_n/1388049 安憶的測試:
![安憶的測試](https://user-images.githubusercontent.com/59136112/120663861-01068680-c4bd-11eb-9e9a-af568a13ce6a.png)

https://t.me/wikipedia_zh_n/1388060 自己的測試:
![自己的測試](https://user-images.githubusercontent.com/59136112/120663887-082d9480-c4bd-11eb-9ea9-0998090183af.png)

**Comment by hamishinyuu** [comment]
理论上来说只有wgPageContentModel为wikitext的不会有这个问题。参见上一次的 #115

**Comment by AnYiLin** [comment]
没太关注这个仓库，站内好像在研究给非wikitext挂模板的事，这里是还没来得及跟进吗？

**Comment by Xi-Plus** [comment]
@AnYiLin #215 #222
