### ISSUE TITLE
部分編輯沒有加入Twinkle標籤

### ISSUE THREAD

**Issue by Xi-Plus** [Xi-Plus/twinkle#3]

**Comment by Wetitpig** [comment]
沒有加入甚麼標籤？

**Comment by Xi-Plus** [comment]
@Wetitpig [Twinkle](https://zh.wikipedia.org/w/index.php?title=Special:RecentChanges&tagfilter=Twinkle)。

**Comment by Xi-Plus** [comment]
發現刪除時沒有加入標籤

**Comment by Xi-Plus** [comment]
Resolved in 0fe947a and 00bc986.
