### ISSUE TITLE
非管理员关闭存废讨论选项

### ISSUE THREAD

**Issue by drizmiz** [Xi-Plus/twinkle#33]
根据Wikipedia:關閉存廢討論指引，非管理员关闭存废讨论包含①快速删除②快速保留③提报到版权验证讨论④请求无效⑤提交理由消失⑥暂时保留⑦无共识保留，共七种情形。但目前的Twinkle选择非管理员关闭存废讨论选项之后不能选择暂时保留。

**Comment by Hamishcn** [comment]
Affected module:
- close

**Comment by Hamishcn** [comment]
Affected module:
- close
