### ISSUE TITLE
morebits: Use csrftoken obtained via meta=tokens

### ISSUE THREAD

**Issue by Hamishcn** [Xi-Plus/twinkle#43]
- azatoth/twinkle@0bd6b92 morebits: Use csrftoken obtained via meta=tokens

**Comment by Xi-Plus** [comment]
需要測試來確保修改沒問題。

**Comment by Xi-Plus** [comment]
dependencies是指package.json裡面那些。

**Comment by Hamishcn** [comment]
block有大問題。
