### ISSUE TITLE
提删重定向问题

### ISSUE THREAD

**Issue by drizmiz** [Xi-Plus/twinkle#55]
提删他人建立的重定向时，小工具先放置删除模板，于是该条目就会变成自己建立的，而跳过通知。

**Comment by Hamishcn** [comment]
未复现，能否提供具体案例？
![Screenshot_2020-06-18-12-33-31-992_com android chrome](https://user-images.githubusercontent.com/39620264/84978765-5472ae00-b160-11ea-8599-3ef8517f740d.jpg)

**Comment by Xi-Plus** [comment]
執行順序為：
* tryTagging
  * taggingArticle
  * main
    * getCreator
確實可能先張貼模板（taggingArticle）才檢查建立者（getCreator）

**Comment by Hamishcn** [comment]
> 執行順序為：
> 
> * tryTagging
>   
>   * taggingArticle
>   * main
>     
>     * getCreator
>       確實可能先張貼模板（taggingArticle）才檢查建立者（getCreator）

不过getCreator不应该也只是获取到建立者而不是最近贡献者吗？

**Comment by Xi-Plus** [comment]
現在已經改成查詢「第一個不是重定向」版本的編輯者了。

**Comment by drizmiz** [comment]
![image](https://user-images.githubusercontent.com/57165742/85303284-dc4c1580-b4dc-11ea-801d-69e4795703bb.png)
如图，若查詢「第一個不是重定向版本」的編輯者就会在提删重定向时出现此问题。能否在提删重定向时特殊处理？

**Comment by drizmiz** [comment]
@Hamishcn 如图是复现的情况。
