### ISSUE TITLE
G11為2倍大失效

### ISSUE THREAD

**Issue by lcw861018** [Xi-Plus/twinkle#70]
目前：已於Twinkle/偏好設定勾選擴大CSD G11的按鈕，但無其顯示為正常效果。
使用瀏覽器：Google Chrome 83.0.4103.106 。

**Comment by Xi-Plus** [comment]
問題已確認
自從 eca0070f58b3a44637383b9c5fbbfefee3d7f052 (2020-03-12) 起，style屬性只應用在label上，而不會應用在radio上
https://github.com/Xi-Plus/twinkle/blob/561b3ea1fb617275395b0b0c3ffabe6428b9aa8f/morebits.js#L406-L409
https://github.com/Xi-Plus/twinkle/blob/561b3ea1fb617275395b0b0c3ffabe6428b9aa8f/modules/twinklespeedy.js#L436-L439

**Comment by Hamishcn** [comment]
Affected module:
- speedy
