### ISSUE TITLE
Merge [ARV] Cleanup: Don't save single-use api variables

### ISSUE THREAD

**Issue by Xi-Plus** [Xi-Plus/twinkle#83]
https://github.com/azatoth/twinkle/commit/d5adb87ce553eae42bf5c6f4c883c4421d1571b6
等待 #82 #86 合併

**Comment by Hamishcn** [comment]
@Xi-Plus 請決定本issue和 #86 的priority，並移除question。

**Comment by Xi-Plus** [comment]
等待 #86 合併

**Comment by Hamishcn** [comment]
無single use api
